name: remote_screen_mobile
description: Remote Screen Mobile V2 viewer with Windows audio playback.
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
