name: remote_screen_mobile_v22
description: Remote Screen Mobile V2.2 with native PCM system audio.
publish_to: 'none'
version: 0.2.2+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
